// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcePWykFQYQcioWBzXxYrZ6hSdIwvRAvk',
    appId: '1:1015140364717:web:cd40e955c1ee61c3e5f124',
    messagingSenderId: '1015140364717',
    projectId: 'evently-dccb8',
    authDomain: 'evently-dccb8.firebaseapp.com',
    storageBucket: 'evently-dccb8.firebasestorage.app',
    measurementId: 'G-FN60WB2493',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvX0XghcSHh3PGzspYg3fGo3GnJDnwckk',
    appId: '1:1015140364717:android:d1c6b0f9f6e6f369e5f124',
    messagingSenderId: '1015140364717',
    projectId: 'evently-dccb8',
    storageBucket: 'evently-dccb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsgI5ticBH8zSsTJY_oBJaHEhKTlqxeo8',
    appId: '1:1015140364717:ios:4028b965c902be4ee5f124',
    messagingSenderId: '1015140364717',
    projectId: 'evently-dccb8',
    storageBucket: 'evently-dccb8.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsgI5ticBH8zSsTJY_oBJaHEhKTlqxeo8',
    appId: '1:1015140364717:ios:4028b965c902be4ee5f124',
    messagingSenderId: '1015140364717',
    projectId: 'evently-dccb8',
    storageBucket: 'evently-dccb8.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcePWykFQYQcioWBzXxYrZ6hSdIwvRAvk',
    appId: '1:1015140364717:web:05ce02884a9c3259e5f124',
    messagingSenderId: '1015140364717',
    projectId: 'evently-dccb8',
    authDomain: 'evently-dccb8.firebaseapp.com',
    storageBucket: 'evently-dccb8.firebasestorage.app',
    measurementId: 'G-TZ2G1EMS92',
  );

}